name: aip

services:
    express:
        build: ./express
        restart: unless-stopped
        ports:
            - 3000:3000/tcp
        volumes:
            - ./.env:/app/.env
            # - /path/to/ssl/fullchain.pem:/usr/src/app/ssl/fullchain.pem
            # - /path/to/ssl/privkey.pem:/usr/src/app/ssl/privkey.pem
        depends_on:
            mongo:
                condition: service_healthy
            kafka:
                condition: service_healthy

    python:
        build: ./python
        restart: unless-stopped
        volumes:
            - ./.env:/app/.env
        depends_on:
            mongo:
                condition: service_healthy
            kafka:
                condition: service_healthy

    nextjs:
        build: ./nextjs
        restart: unless-stopped
        ports:
            - 80:3000/tcp
        volumes:
            - ./.env:/app/.env
        depends_on:
            express:
                condition: service_started

    mongo:
        image: mongo:jammy
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo-admin
            MONGO_INITDB_ROOT_PASSWORD: <password>
            AIP_ADMIN_USERNAME: aip-admin
            AIP_ADMIN_PASSWORD: <password>
            MONGO_INITDB_DATABASE: automated_interview_platform_db
        ports:
            - 27017:27017/tcp
        volumes:
            - db-data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 5s
            timeout: 5s
            retries: 10

    zookeeper:
        image: zookeeper:latest
        ports:
            - 2181:2181/tcp

    kafka:
        image: wurstmeister/kafka:latest
        restart: unless-stopped
        ports:
            - 9092:9092/tcp
        expose:
            - "9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "resume-upload:1:1,feedback-request:1:1"
        depends_on:
            zookeeper:
                condition: service_started
        healthcheck:
            test: kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    db-data:
